# nonk8s
version: 0.0.1
kind: DataContract
apiVersion: v3.0.1
id: 305b72db-e2dc-4817-87af-8b97aec038e7
name: Ecommerce Order Management Data Contract
status: draft
domain: ecommerce
dataProduct: order management
description:
  purpose: describes order management data
  customProperties:
    - property: namespace
      value: com.example.ecommerce.order
schema:
  - name: Order
    description: contains order data
    properties:
      - name: id
        description: the order identifier
        logicalType: string
        physicalType: string
        required: true
      - name: name
        description: the order name
        logicalType: string
        physicalType: string
        required: true
  - name: OrderLine
    description: contains order line data
    properties:
      - name: id
        description: the order line identifier
        logicalType: string
        required: true
      - name: order_id
        description: the order identifier
        logicalType: string
        required: true
      - name: product_id
        description: the identifier of the product ordered
        logicalType: string
        required: true
      - name: quantity
        description: number of items ordered
        logicalType: integer
        exclusiveMinimum: "0"
        required: true

